# MultiBN constants
MBN_SESSION_TCP_INIT = 0
MBN_SESSION_TCP_QUIT = 1
MBN_SESSION_TCP_CLIENT_NUMBER_OF_LOCAL_PLAYERS = 2
MBN_SESSION_TCP_NEW_CLIENT = 3
MBN_SESSION_TCP_NEW_CLIENT_NUMBER = 4
MBN_SESSION_TCP_NEW_CLIENT_ASSIGNED_CLIENTS_ID = 5

# datagram shape
# data|data type|data|crc
MBN_CON_UDP_CLIENT_DATA = 100
MBN_CON_UDP_CLIENT_DATA_LOOP_START = 101
MBN_CON_UDP_CLIENT_DATA_LOOP_END = 102
MBN_CON_UDP_CLIENT_DATA_LOOP_NUMBER = 103
MBN_CON_UDP_CLIENT_DATA_PING = 104

# time in ms
MBN_CON_UDP_CLIENT_DATA_PING = 5000