# MultiBN constants
MBN_SESSION_TCP_INIT_TCP = 0
MBN_SESSION_TCP_QUIT_TCP = 1
MBN_SESSION_TCP_NEW_CLIENT = 2


# data|data type|data|crc
MBN_CON_UDP_CLIENT_DATA_UDP = 100
MBN_CON_UDP_CLIENT_DATA_UDP = 101